# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyTmuxFzf < Formula
  desc "Fast tmux session manager (fzf picker)"
  homepage "https://github.com/alchemmist/lazy-tmux"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.3.0/lazy-tmux_darwin_amd64_fzf.tar.gz"
      sha256 "430a4e24dc456d57c8de2c3fe30672faff3339baf50f9c8b2fd1de8405ce3730"

      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.3.0/lazy-tmux_darwin_arm64_fzf.tar.gz"
      sha256 "ab506e96f0646d7926279761e11f9f1f2546cd03a04e67dc106e962df0f4c58a"

      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.3.0/lazy-tmux_linux_amd64_fzf.tar.gz"
      sha256 "343e5430349e1d4e0d496752c0be24b35ed004b9b069b464b114ffa5da867a6a"
      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.3.0/lazy-tmux_linux_arm64_fzf.tar.gz"
      sha256 "5397d32dd10a972d8eb2526c59a88bfbcf77f8645b526c038505896dbe8ee45d"
      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
  end

  test do
    system "#{bin}/lazy-tmux-fzf", "--version"
  end
end
