# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyTmuxFzf < Formula
  desc "Fast tmux session manager (fzf picker)"
  homepage "https://github.com/alchemmist/lazy-tmux"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.10/lazy-tmux_darwin_amd64_fzf.tar.gz"
      sha256 "447a649f37bb98155caeab61622cd353283d6ebd6ef70ca71b21afa13240ec81"

      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.10/lazy-tmux_darwin_arm64_fzf.tar.gz"
      sha256 "e8cd75665ba7610db4e758479ca84f3beac3d86ae1a62d3c2e899e171c91e49f"

      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.10/lazy-tmux_linux_amd64_fzf.tar.gz"
      sha256 "2dff8c8086a21d65e1fff8c82c1c664029bbc0cbcee8e00a67e8159d61b9b4b7"
      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.10/lazy-tmux_linux_arm64_fzf.tar.gz"
      sha256 "c1457bc04e57b1defd5ba3c741c795703f0590d38b6a8d061c8a47d8420318cb"
      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
  end

  test do
    system "#{bin}/lazy-tmux-fzf", "--version"
  end
end
