# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyTmux < Formula
  desc "Fast tmux session manager with TUI picker"
  homepage "https://github.com/alchemmist/lazy-tmux"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.2.4/lazy-tmux_darwin_amd64.tar.gz"
      sha256 "94b39fdafcdd86589460a2bf72cf2606534b5353d6da8fa99686b052240996cc"

      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.2.4/lazy-tmux_darwin_arm64.tar.gz"
      sha256 "4c1d241247104b3cb76f3c33d4bd9bebc8987d92dfa85f57d348142660790952"

      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.2.4/lazy-tmux_linux_amd64.tar.gz"
      sha256 "448dca7b138e56017d65d35a268a15d21c89b5711210fa98df0ff544329851ff"
      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.2.4/lazy-tmux_linux_arm64.tar.gz"
      sha256 "226bd601b93ff1ade74fef5bc0f5754cd7aa59778f79df2dbfd0addd438ce29f"
      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
  end

  test do
    system "#{bin}/lazy-tmux", "--version"
  end
end
