# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyTmux < Formula
  desc "Fast tmux session manager with TUI picker"
  homepage "https://github.com/alchemmist/lazy-tmux"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.2.0/lazy-tmux_darwin_amd64.tar.gz"
      sha256 "b3f6e343872f7eed227f06a5102bfda772b4cb99a353bd602af670429d2c6b65"

      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.2.0/lazy-tmux_darwin_arm64.tar.gz"
      sha256 "02b7266d04689cab8d6109947d09a53a84c59f9acf70f3390ef96a13b70ea922"

      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.2.0/lazy-tmux_linux_amd64.tar.gz"
      sha256 "47d364aac19b55cd536ed105adb76ebc629e6cbbc1e060b0f9ec0db4502426a9"
      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.2.0/lazy-tmux_linux_arm64.tar.gz"
      sha256 "80aa10c27d3fe387e2d0768aab45fbf423fcf18b6d3ff0bd0e8ed004643678ce"
      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
  end

  test do
    system "#{bin}/lazy-tmux", "--version"
  end
end
