# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyTmux < Formula
  desc "Fast tmux session manager with TUI picker"
  homepage "https://github.com/alchemmist/lazy-tmux"
  version "0.1.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.23/lazy-tmux_darwin_amd64.tar.gz"
      sha256 "e39a79f56fcc5bf7cdaa64fbb6cc933ca6ff6dada798c5a0487cf8871b01bf8a"

      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.23/lazy-tmux_darwin_arm64.tar.gz"
      sha256 "f7793f7861684662a26b651b28a9a68de0b7ed1e994a295010f4de62dc9c0d10"

      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.23/lazy-tmux_linux_amd64.tar.gz"
      sha256 "fa9dd01930fdd539bcfa2b3de07d86101dc1b8c5d23bd407bce75306b4e8a8cf"
      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.23/lazy-tmux_linux_arm64.tar.gz"
      sha256 "9d8faa68341719e89410a760e00193ff9556b33768bf2e1cc5ba5785fb912b14"
      define_method(:install) do
        bin.install "lazy-tmux"
      end
    end
  end

  test do
    system "#{bin}/lazy-tmux", "--version"
  end
end
