# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyTmuxFzf < Formula
  desc "Fast tmux session manager (fzf picker)"
  homepage "https://github.com/alchemmist/lazy-tmux"
  version "0.1.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.18/lazy-tmux_darwin_amd64_fzf.tar.gz"
      sha256 "9712e143bab912e64dbcc9ac4d4b2db640bff851dd39386cfc21b2ca8600629b"

      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.18/lazy-tmux_darwin_arm64_fzf.tar.gz"
      sha256 "567e766ce49b8966766e58275cfad521d2d7d4a84b1b32f75f221960d3256351"

      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.18/lazy-tmux_linux_amd64_fzf.tar.gz"
      sha256 "f23c0d5e28c5b59efece76f030726261c3ee361c09250284d47d9f078235e519"
      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.18/lazy-tmux_linux_arm64_fzf.tar.gz"
      sha256 "e4f67374e771ad512546543bf9ba8c5ae896cf63a45f4f7bc6ff4a79d9aaf31d"
      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
  end

  test do
    system "#{bin}/lazy-tmux-fzf", "--version"
  end
end
