# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyTmuxFzf < Formula
  desc "Fast tmux session manager (fzf picker)"
  homepage "https://github.com/alchemmist/lazy-tmux"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.13/lazy-tmux_darwin_amd64_fzf.tar.gz"
      sha256 "fb7bb5125c91c7541d39eec919e5a416c7b2d703039b3cc1276698460fe060f0"

      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.13/lazy-tmux_darwin_arm64_fzf.tar.gz"
      sha256 "bde80691d7e7e265e43d0dd940c9324c637d78239e7ec7cc30e05e72f67c2a71"

      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.13/lazy-tmux_linux_amd64_fzf.tar.gz"
      sha256 "574ace88ea9d3011a35352ee29f6a71b43e3d1599072fc429498aa36ccbbd9f5"
      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alchemmist/lazy-tmux/releases/download/v0.1.13/lazy-tmux_linux_arm64_fzf.tar.gz"
      sha256 "c75f939d846d27b2dbb094b219e8f1c653e93e391dfea1c67167d860baab0cf1"
      define_method(:install) do
        bin.install "lazy-tmux" => "lazy-tmux-fzf"
      end
    end
  end

  test do
    system "#{bin}/lazy-tmux-fzf", "--version"
  end
end
